### ISSUE TITLE
Order (and a typo?)

### ISSUE THREAD

**Issue by millette** [anarcat/terms-benchmarks#2]
I'm a bit puzzled by this table and comment under it:

| Terminal            | All | Order | From right |
| ------------------- | --- | ----  | ---------- |
| [mlterm][]          |  ✓  |  ✓    |     ✓      |
| [xterm][]           |  x  |  x    |     x      |

> Note that mlterm 3.5, as packaged in Debian, does not render all characters properly, most of them being rendered as boxes.

Did you mean ```xterm``` in the comment, instead of ```mlterm```?

**Comment by anarcat** [comment]
On 2018-03-29 18:57:14, Robin Millette wrote:
> I'm a bit puzzled by this table and comment under it:
>
> | Terminal            | All | Order | From right |
> | ------------------- | --- | ----  | ---------- |
> | [mlterm][]          |  ✓  |  ✓    |     ✓      |
> | [xterm][]           |  x  |  x    |     x      |
>
>> Note that mlterm 3.5, as packaged in Debian, does not render all characters properly, most of them being rendered as boxes.
>
> Did you mean ```xterm``` in the comment, instead of ```mlterm```?

I do not: mlterm works fine in the latest version, just not in the older
version packaged in Debian.

Should I clarify?

**Comment by millette** [comment]
Maybe use a * instead of ✓ next to mlterm in the table? It's not a big deal, but it confused me enough to reach out.
